name: build openwrt
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build ${{matrix.version}} - ${{matrix.target}}
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [NBG6817, uaplite, erx]
        version: [openwrt-19.07]

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Checkout openwrt source 
        uses: actions/checkout@v2
        with:
          repository: openwrt/openwrt
          path: openwrt
          ref: ${{ matrix.version }} 

      - name: Setup env
        run: |
           sudo -E apt-get -qq update
           sudo -E apt-get -qq install build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig
    
      - name: Update feeds
        run: cd openwrt && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt && ./scripts/feeds install -a
      
      #- name: Custom Settings
      #  run: |
      #    sed -i 's/192.168.1.1/192.168.10.6/g' openwrt/package/base-files/files/bin/config_generate
          
      - name: Copy Config
        run: cp ${{ matrix.target }}.config openwrt/.config
        
      - name: make defconfig
        run: cd openwrt && make defconfig

      - name: Download package
        id: package
        run: cd openwrt && make download -j8
      
      - name: Compile the firmware
        id: compile
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j12|| make -j2 V=s
          
      - name: Organize files
        id: organize
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages

      - name: rsync to server
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: openwrt/bin/targets/
          remote_path: public/${{ matrix.version }}
          remote_host: ${{ secrets.REPO_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.REPO_USER }}
          remote_key: ${{ secrets.REPO_SSH_KEY }}