name: build openwrt
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build ${{matrix.version}} - ${{matrix.target}}
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [NBG6817, uaplite, fb3370]
        version: [openwrt-21.02]
        repo: [openwrt/openwrt]
        include:
          - target: NBG6817
            version: openwrt-21.02-nss-qsdk10.0
            repo: ACwifidude/openwrt
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Checkout openwrt source 
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }} 
          path: openwrt
          ref: ${{ matrix.version }} 


      - name: Setup env
        run: |
           sudo -E apt-get -qq update
           sudo -E apt-get -qq install build-essential rsync asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget swig
    

      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
          
      - name: Configuration Customization - ${{ matrix.target }}
        env:
          CONFIG_FILE: '${{ matrix.target }}.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          #cd openwrt && make defconfig
        

      - name: Download package
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      
      - name: Build firmware
        working-directory: ./openwrt
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: Organize files
        id: organize
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt ${{ matrix.target }}
          path: openwrt/bin
