name: build openwrt
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build ${{matrix.version}} - ${{matrix.target}}
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [uaplite, erx]
        version: [openwrt-22.03]
        repo: [openwrt/openwrt]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Checkout openwrt source 
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repo }} 
          path: openwrt
          ref: ${{ matrix.version }} 


      - name: Setup env
        run: |
           sudo -E apt-get -qq update
           sudo -E apt-get -qq install time git-core subversion build-essential gcc-multilib libncurses5-dev zlib1g-dev gawk flex gettext wget unzip file grep rsync python3 python3-distutils
    

      - name: Update & Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      
          
      - name: Configuration Customization - ${{ matrix.target }}
        env:
          CONFIG_FILE: '${{ matrix.target }}.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          #cd openwrt && make defconfig
        

      - name: Download package
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      
      - name: Build firmware
        working-directory: ./openwrt
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          
      - name: Organize files
        id: organize
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt ${{ matrix.target }}
          path: openwrt/bin
